### PR TITLE
transaction-fee

### PR DESCRIPTION
**Pull request by igorsyl**
PR to be completed by @netrome

This PR addresses the 2.1 test item:
> Verify that transactions now pay transaction fees before they are executed, such that any transaction with a runtime-caught CheckError is mined and the paying account is billed the transaction fee. - @igorsyl / @netrome

taken from https://github.com/stacks-network/stacks-blockchain/discussions/3242

I wrote instructions for testing using the live 2.1 testnet and command line tools here:
https://gist.github.com/igorsyl/7da553fc7cf19b9578abdc97d76eb825

The contract code needs to be changed to trigger a Runtime Unchecked CheckError. We can check with Jude on the exact contract code to use.

This PR proposes to add integration test to check the desired behavior.
To run the integration test:
```
yarn install
yarn test transaction-fee
```

### CODE REVIEW

**Comment by netrome** [comment]
I'm getting a FetchError when running the transaction-fee test case locally:
```
yarn test transaction-fee

 RUNS  tests/integration/clarity/natives/transaction-fee.spec.ts
LogData { occurred_at: "Dec 19 11:11:18.581005", message: "Initiating Devnet boot sequence (working_dir: /tmp/stacks-test-1671448276971)", level: Info }
LogData { occurred_at: "Dec 19 11:11:18.581027", message: "Creating network stacks-2-1-testing-1.devnet", level: Info }
LogData { occurred_at: "Dec 19 11:11:18.581028", message: "Starting bitcoin-node", level: Info }
LogData { occurred_at: "Dec 19 11:11:20.985405", message: "Configuring bitcoin-node", level: Info }
LogData { occurred_at: "Dec 19 11:11:21.986312", message: "Waiting for bitcoin-node", level: Info }
LogData { occurred_at: "Dec 19 11:11:23.098809", message: "Starting stacks-node", level: Info }
LogData { occurred_at: "Dec 19 11:11:26.060104", message: "Stacks block #0 anchored in Bitcoin block #100 includes 7 transactions", level: Info }
LogData { occurred_at: "Dec 19 11:11:26.131103", message: "Bitcoin block #101 received", level: Debug }
LogData { occurred_at: "Dec 19 11:11:37.155608", message: "Bitcoin block #102 received", level: Debug }
LogData { occurred_at: "Dec 19 11:11:47.014556", message: "Bitcoin block #103 received", level: Debug }
LogData { occurred_at: "Dec 19 11:11:47.214839", message: "Genesis Stacks block anchored in Bitcoin block #103 includes 2 transactions", level: Info }
LogData { occurred_at: "Dec 19 11:11:56.867469", message: "Bitcoin block #104 received", level: Debug }
LogData { occurred_at: "Dec 19 11:11:57.005752", message: "Stacks block #2 anchored in Bitcoin block #104 includes 1 transactions", level: Info }
LogData { occurred_at: "Dec 19 11:12:06.619150", message: "Bitcoin block #105 received", level: Debug }
LogData { occurred_at: "Dec 19 11:12:06.759825", message: "Stacks block #3 anchored in Bitcoin block #105 includes 1 transactions", level: Info }
 FAIL  tests/integration/clarity/natives/transaction-fee.spec.ts (59.943 s)06 received", level: Debug }
  transaction-fee
    ✕ fee is charged prior to execution (59686 ms)

  ● transaction-fee › fee is charged prior to execution

    FetchError: request to http://localhost:10024/v2/accounts/ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM?proof=0 failed, reason: connect ECONNREFUSED ::1:10024

      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1491:11)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        59.973 s, estimated 60 s
Ran all test suites matching /transaction-fee/i.
thread '<unnamed>' panicked at 'receiving on a closed channel', components/stacks-devnet-js/src/lib.rs:191:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@igorsyl is this expected behavior?

**Comment by netrome** [comment]
> @netrome I do not experience this issue. Can you try running `yarn test` using the `main` branch?

Running `yarn test` on the `main` branch now. I've got 11 failing tests so far with the same FetchError. This confirms my suspicion that it's a problem with my environment.

**Comment by netrome** [comment]
The problem was that `localhost` resolved to ipv6 ::1 instead of 127.0.0.1. Adding `127.0.0.1 localhost` to my `/etc/hosts` solved it. Now the test works for me.

**Comment by diwakergupta** [comment]
> @lgalabru We can't add reviewers to this PR. Can you grant our team contributor access to this repo? Thanks!
> 
> https://github.com/orgs/Trust-Machines/teams/core-engineering

@igorsyl I think the above link is private, doesn't open for me. Can you just tag reviewers in a comment for now and I can manually add them.

**Comment by lgalabru** [comment]
We just released `v1.3.0` of `stacks-devnet-js` which include some pretty invasive changes - but way more stable (as long as you don't run too many tests at once - I'm still investigating that part).
I migrated the test file from this PR to `v1.3.0` in this branch https://github.com/hirosystems/stacks-2-1-testing/pull/12, and added @igorsyl and @netrome as contributors in this repo, feel free to close this PR when the rest of this PR is migrated!

**Comment by netrome** [comment]
After some hiccups with `stacks-devnet-js` `v1.3.0`, we've got it working in [the other PR](https://github.com/hirosystems/stacks-2-1-testing/pull/12). Closing this one. The other one is ready for review.

**Pull request closed without merging**
